# Generated by Django 4.0.3 on 2022-04-14 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_alter_mlalgorithmstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlalgorithm',
            options={'verbose_name': 'ML algorithm'},
        ),
        migrations.AlterModelOptions(
            name='mlalgorithmstatus',
            options={'verbose_name': 'ML algorithm status', 'verbose_name_plural': 'ML algorithm statuses'},
        ),
        migrations.AlterModelOptions(
            name='mlrequest',
            options={'verbose_name': 'ML request'},
        ),
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parent_mlalgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.mlalgorithm', verbose_name='parent ML algorithm'),
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('algorithm_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_A', to='endpoints.mlalgorithm')),
                ('algorithm_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_B', to='endpoints.mlalgorithm')),
            ],
            options={
                'verbose_name': 'A/B Test',
            },
        ),
    ]
